### ISSUE TITLE
Using onItemClickListener

### ISSUE THREAD

**Issue by rogerg9999** [umano/MultiItemRowListAdapter#2]
How can I work with onItemClickListener or onClickListener.
Thanks

**Comment by tagrudev** [comment]
I don't think it's implemented ? I wonder if this repo is still maintained

**Comment by tokudu** [comment]
Yes, this library is maintained. To answer your question: it can't. Since each row in the listview represents multiple items, the onClickListener in listview is meaningless. You need to attach our own listeners in wrapped adapter.
