### ISSUE TITLE
NullPointer when set 2 items per row and listview has odd number of items. For example 11, 13, 15,...

### ISSUE THREAD

**Issue by bimemto** [umano/MultiItemRowListAdapter#3]
When I set itemPerRow is 2 and my list adapter has odd number of items, there will be a space at the last item of the last row. Then when I scroll up, it throw NullPointerException. Can you check and fix it? Thanks.

**Comment by tagrudev** [comment]
Yeah I lost an hour on that :-1:  should have checked the issues first

**Comment by tokudu** [comment]
Thanks for the report. Marking as a bug.

**Comment by tokudu** [comment]
Fixed in: https://github.com/umano/MultiItemRowListAdapter/commit/a5e3e4e50e05e2ee95d1c0d261fd56cd85381e58
